### PR TITLE
runs count browsers in parallel, spawning a new task after the previous

### PR DESCRIPTION
**Pull request by frosty00**
Hi there,

I'm jadenpls from reddit.

I have been using your code since yesterday to test out if I could break google recaptcha. Worked ~5 times on my home ip before they blocked it from audio captchas. I am currently attempting to scrape as many free proxies as possible to make this work consistently. 

This change opens and keeps `count` browsers open instead of just running count browsers at once until they fail.

Is there any reason why you have `get_proxies` declared twice, this could probably be refactored also. Many thanks for the great app I will be making more PRs in the future.

### CODE REVIEW

**Comment by mikeyy** [comment]
Hello jadenpls(frosty00),

I will be away for most of the day due to Father's day. When time is available I will review the code further before making my decision.

As for the get_proxies, it must have been an oversight on my end. Examples weren't as diligently cared for as the main Solver class, since I expected others to treat them as a  guide and hopefully build on from them or start from scratch using the Solver library. I may plan on giving them a more thorough inspection and maybe include them within the project but it hasn't been a priority.

**Comment by mikeyy** [comment]
Weird, no idea why those commits from presentation refrenced your pull requests. Wasn't my intention, hah.

After reviewing the code, wouldn't it be easier to just spawn the threads and place each individual one in a while loop?

**Comment by frosty00** [comment]
@mikeyy it would be easier but not fully asynchronous. Since all the calls in the library are already async functions it would make more sense to run them in one event loop, instead of multiple threads. At the end of the day it is up to personal preference anyway, and each method has its merits, and I expect users will just use the solver class or app.py in their application.

**Comment by frosty00** [comment]
Each pull request and issue has a sequential nonce, for example this is PR #2 as you can see in the url. If you type #n in a commit message and that number is referenced as a github issue or PR github will automatically link the commits.

**Comment by mikeyy** [comment]
Ah, gotcha. Thanks for the information, this git stuff is a handful.

I've been working on making the pull request a bit more Pythonic, among other things with the Solver. I think I've achieved some success, will pull a commit here in a sec.

**Comment by frosty00** [comment]
https://github.com/mikeyy/nonoCAPTCHA/blob/6d834b6713e80e6409f54f623539c2a7f977a9ea/solver.py#L117

This line is throwing an error in my code

**Comment by mikeyy** [comment]
Pushed another commit, see if that method works on your end.

**Pull request closed without merging**
