### PR TITLE
more attempts at image solving

### PR DESCRIPTION
**Pull request by frosty00**
Not ready to be merged.

I implemented a word similarity library and tried to use GRIS and the word similarity to solve images. 

Not particular successful so far...

### CODE REVIEW

**Comment by frosty00** [comment]
I think I will have more success on the 4x4 images which split one single image, as oppose to the 3x3 composed of multiple images.

**Comment by frosty00** [comment]
Check your emails, I have an offer that might interest you.

**Comment by mikeyy** [comment]
> Check your emails, I have an offer that might interest you.

You already sent? I don't see it. 

Sorry about being MIA, something important came up.

**Comment by frosty00** [comment]
I sent it to your notifications@github.com email address by accident, resent.

**Comment by mikeyy** [comment]
On hold due to issues, in particular one's that aren't directly inline with image solving and especially those that change the core code, example `base.py` where you copy the file right back into the package folder.  We've had this discussion. I will have no choice to leave these changes out but am happy to merge your progress with the image solving, or even modifications that are for readability or performance, or bug fixes. Feel free to share your ideas if I'm misunderstanding.

**Comment by frosty00** [comment]
I am busy with my new job @ https://github.com/ccxt/ccxt#team but hope to spend some money on proxies to try play with the library again sometime soon :)

**Comment by mikeyy** [comment]
It's good to hear from you, and with great news, congrats man! It's the same here, I've had to place the project on the sidelines for any major changes.

Keep in touch

**Pull request closed without merging**
