### PR TITLE
can now store multiple cookies, fixed util.serialize and deserialize

### PR DESCRIPTION
**Pull request by frosty00**

### CODE REVIEW

**Comment by mikeyy** [comment]
Nice! Gonna merge this now before any conflicts.

**Comment by frosty00** [comment]
Do you mind sharing like 20 proxies with me so I can help develop this library as currently my home ip is blocked and web proxies are also blocked. Eventually I will buy my own...

**Comment by mikeyy** [comment]
They are locked to a single IP but send me an email, mikeyy@mikeyy.com

**Comment by frosty00** [comment]
Sent

**Pull request merged**
