### PR TITLE
add initial automated tests

### PR DESCRIPTION
**Pull request by frosty00**
This will run each time something is pushed to this repository. I would also like to add a webhook or test script that tests the captcha solver is still working but we have to overcome the issue of how to manage the proxies first.

### CODE REVIEW

**Comment by mikeyy** [comment]
Awesome. Yeah, I can host a proxy server that just proxies the request to a list of the fastest proxies in my list but then there is still no guarantee they aren't blocked from audio.

**Comment by frosty00** [comment]
I think what we will have to do for tests is either

* run `app.py` on your server that is connected to proxies (you would have to always run this publicly)
* 
```
for i in range(x):
    result = await main()
    if result:
        # test succeeded
         break
```

**Comment by mikeyy** [comment]
Awesome. Yeah, I can host a proxy server that just proxies the request to a list of the fastest proxies in my list but then there is still no guarantee they aren't blocked from audio.

All we really have to do to make backconnect proxies work is fetch the real IP address and use that as the unique identifier instead of the proxy server, I would think.

**Comment by frosty00** [comment]
> All we really have to do to make backconnect proxies work is fetch the real IP address and use that as the unique identifier instead of the proxy server, I would think.

Seems like an unnessary http request. Could you setup the server in such a way that it just sends the ip and port of the proxy we're trying to connect to? This also avoids having to route all traffic through your server, meaning responses should come back faster.

**Pull request merged**
