### PR TITLE
seperate commits

### PR DESCRIPTION
**Pull request by frosty00**
audiosolver, solver and GRIS share some methods that why I created `base.py`

### CODE REVIEW

**Comment by frosty00** [comment]
Yep no worries, I could tell that the code still needed some polishing. Should have more free time now to work on the project. I see you've incorporated the base class and I'll try to come up with something for the image solving. 

How I picture the finished library logic flow:

screen shot 2018-06-24 at 09 56 31

Currently the audio captcha has an over 95% (?) success rate if the audio captcha is opened, but it has a high chance of never being able to run.

**Comment by mikeyy** [comment]
I agree, that is a bit how I've been visualizing the flow. 👍 I've been trying to make good use of the Base class, I tried passing along proc_id/proc_count with it so I didn't have to pass self.log to the solvers but it would +1 the id when the solver initiated as well, so... 

That would be great, if you wouldn't mind working on that. I just haven't had the time with trying to clean up the code and have it turn into a big mess. 

Yeah, and that's a big if, depending on the persons' proxies, if the audio captcha is opened. 

My next step should be a proxy manager then, on top of all the code refactoring of course. I've been looking around for a good NoSQL async supported server/client but no luck so far. I saw shelfdb but it was causing all sorts of problems. Might have to go mongo, or postgres, but I think they are too large for proxy management. What I plan on doing is something like this, incoming psuedocode:

```python
timeout = 30
def update_proxy_used(proxy):
    db('proxies').update({
            'proxy': proxy,
            'active': False,
            'last_used': time.time()
        }
    ).run()


def update_proxy_active(proxy):
    db('proxies').update({'proxy': proxy, 'active': True}).run()


def get_proxy():
    query = db('proxies').first(proxies['last_used'] > time.time() and proxies['active'] == False and proxies['banned'] == False)
    return query.run()


def insert_proxy():
    db('proxies').insert({
            'proxy': '127.0.0.1:1000',
            'active': False,
            'banned': False,
            'last_used': time.time()
        }
    ).run()


async def do_something_with_proxy():
    await asyncio.sleep(5)


async def main():
    await insert_proxy()
    proxy = await get_proxy()
    await update_proxy_active(proxy)
    await do_something_with_proxy()
    await update_proxy_used(proxy)
```

**Comment by frosty00** [comment]
If I were you instead of making a database of dictionaries I would make a set of classes representng each proxy object. 

```
class Proxy:
    def __init__(self, ip):
        self.ip = ip
        self.last_used = 0
        self.active = True

proxies = set(Proxy(ip) for ip in ips)
order_to_use = sorted((p for p in proxies if p.active), key=lambda x: x.last_used)
```

In terms of using a database I would simply call `util.serialize(proxies, file_path)` and `util.deserialize` to save and read the set from the disk.

**Comment by mikeyy** [comment]
Well I'll be darn, that would definitely makes things more simpler! I will have to see how large the file will be as well, I have almost 100,000 active proxies at times and that file alone is around 350kb. Which isn't too bad I guess, I think jQuery is around 330kb or something non-minified.

I use an SQLite database in one of my private projects for proxy management and after one day of usage it gets to around 80mb, lol... Inserting and updating multiple rows sucks too. Even with pragma switches it will go on halt for about 15 seconds every 10 minutes when it reloads the proxy list.

**Pull request closed without merging**
