### PR TITLE
tries to log into google

### PR DESCRIPTION
**Pull request by frosty00**
I've tested this and upon loading the cookies associated with my account I was able to pass the captcha without a proxy, (previously my ip was blacklisted). I will continue to test but it would be really useful if this works :)

### CODE REVIEW

**Comment by mikeyy** [comment]
Nice, this looks good for a starter. What I had in mind was having a list of Google accounts and we keep track of their usage. Once we determine their captchas solving rate limit we can throw them out and set a timer on them. More testing is in order to determine their rate limit. I will have to get my hands on some Google accounts in the mean time.

**Comment by frosty00** [comment]
Yeah in initial testing I've noticed some accounts are blocked and some aren't. Pretty peculiar stuff. Perhaps they have some sort of limit on new/unused accounts.

**Comment by mikeyy** [comment]
I can confidentially say that aged accounts will have a greater success, plus logging in from an IP that resides in it's initial creation or previous login. Albeit I've yet to test this for reCAPTCHA. Will report back here on what I find when I have the chance.

Check this paper as well, http://www.cs.columbia.edu/%7Epolakis/papers/sivakorn_eurosp16.pdf

Preferably section 4.1 Influencing the risk analysis system.

**Comment by frosty00** [comment]
> Surprisingly,  we  conclude  that  it  is  actually  better  for  an
adversary to not use any account at all.

Interesting conclusion, not sure about the data they use to back this claim however.

> Furthermore, each cookie can receive up to 8 checkbox captchas in a day.

They talk about other google tracking cookies being used to influence the captchas, but it doesn't go into detail about which ones.

> This suggests that the image reCaptcha may contain both“control” and unknown images

Classic google using humans to train their AI...

**Comment by mikeyy** [comment]
> Interesting conclusion, not sure about the data they use to back this claim however.

Considering one would have to wait 60 days for any benefit from having an account, solving without an account would be more convenient unless you already have aged phone-verified accounts or are **really** patient.

> They talk about other google tracking cookies being used to influence the captchas, but it doesn't go into detail about which ones.

According to table 3 the cookies they are speaking of just happen to be cookies they used to search and surfed the web with for 9 days.

> EDIT: Brand new accounts do indeed get blocked immediately, I think the article mentioned something about nine days being neccessary.

60 days for accounts, even phone verified. Nine days for cookies. Quite interesting to say the least.

**Comment by frosty00** [comment]
Yes, fortunately I think most people have gmail accounts.

From my experience I found that adding my (main) account helped me get to the audio captcha when before I recieved an "you might be sending automated queries". However, I would be weary about using gmail accounts together with proxies, and perhaps we should add a warning or block the user from doing such. 

What are you opinions on guessing the image captcha given that the audio captcha is blocked when using proxies.

>  In  most  cases  (74%)  we  found
the  number  of  correct  candidate  images  to  be  2

What's your opinion on blind guessing 2 of the 9 images given the audio captcha was blocked when using a proxy? Some of the image recognition techniques are pretty straightforward to implement - one is just a google reverse image search and reading the image tags.

**Comment by mikeyy** [comment]
That sounds like a good idea. I will try to push a new commit sometime tonight (catching up on Silicon Valley's new season...) or at least sometime this week that blindly solves images, and maybe in the future we can use TensorFlow or another API service for image recognition and increase the chances of success dramatically.

Using one account won't be effective, especially if one wants to solve 24/7.  Probably wouldn't be a wise choice to use ones main account for automatic solving. Getting locked from solving captchas is a guarantee but losing your account could be at risk as well. On the other hand, I do know of at least one service we can purchase aged Google phone verified accounts that I can't disclose publicly.

I will work on the image part first and then merge your commit after more review and then will start working on making it effective for multi account use. I will have to plan out a way to store them possibly in their own Chrome profile folders instead of a temporary one each time, this way they can stay logged in. This also leads to having to manage a range of other procedures as well for when they are locked out and then determining where to store the lockout data and for when and how we release them back into the pool of active accounts.  Something to think over.

**Comment by mikeyy** [comment]
> Some of the image recognition techniques are pretty straightforward to implement - one is just a google reverse image search and reading the image tags.

Just saw that, clever idea. I will see how effective it is. Speed is going to be an issue as well. Things that don't need to be ran under the browser should be reallocated under aiohttp.

**Comment by mikeyy** [comment]
Spent a few hours rehauling the code and reorganizing things. Figured it was needed before adding in another solving method. Going to get some rest and hopefully get something going with images later.

**Comment by frosty00** [comment]
Awesome, loving the refactor. I'm reading over it and it seems like you've done some pretty cool stuff with `asyncio.subprocess`. I may make another PR today of general cleanup also.

**Comment by frosty00** [comment]
Could you merge this. I had to deal with alot of merge conflicts and this commit is pretty straightforward.

**Comment by mikeyy** [comment]
Do you think we could offload logging into Google through aiohttp/util.get_page ? I haven't tried it yet myself but either way I'll merge this. I'm doing some extra changes and wouldn't want to cause anymore convenience. Will have to review it afterward for this one time, as much as I'd hate to.

**Comment by frosty00** [comment]
Not sure, typically you need a web driver to be able to store cookies, not sure about loading cookies. Also it involves POST requests and I'm sure google have a ton of security so this is probably the easiest way. 

The only issues that I have with this is that:

* Doesn't store multiple accounts (overwrites each time)
* Uses `await asyncio.sleep(2)` to wait for part of the page to load

If you manage to log in without using a webdriver than feel free to change

**Comment by mikeyy** [comment]
Think I broke something on your latest commit. Was going to investigate the page loading issue but it just quickly closes the browser when I have a gmail account supplied.

**Comment by frosty00** [comment]
just changed how logging is done so hopefully it will be easier to find out what went wrong in the future

**Comment by mikeyy** [comment]
As long as there isn't some Javascript detection mechanism like the reCAPTCHA fiasco it should be doable through HTTP request data. I'll have to look into it after the image solving, or at least once I get some of pieced together.

**Pull request merged**
