### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by frosty00**
I added a utility method and changed how we check for `self.detected`. Whenever a method is called such as `click_reload_button` it will automatically check if we have been detected and raise a `SystemExit` which is usually caught by logic in start and still closes the browser. 

Also the new instance count is useful for async processes since it is easier to keep track of what has happened where.

Lmk your thoughts

### CODE REVIEW

**Comment by frosty00** [comment]
Moving run.py and app.py into examples has introduced a bug for me. I suspect it has something to do with paths, but it is really hard to debug when you have so many `try: except: pass` statements. Could you revert pls.

**Comment by frosty00** [comment]
Ah nvm found the bug

```
        override_js = await util.load_file(
            settings["data_files"]["override_js"]
        )
```

None of these paths work since they were relative paths.

**Comment by mikeyy** [comment]
Dang, what the heck. I didn't think I had applied that commit as of yet. Reverting.

**Comment by frosty00** [comment]
I have fixed it now we're all gucci

**Comment by mikeyy** [comment]
RIP.  I'm in the process of turning the project into a package didn't think I had made that commit, was for after. Sorry for the inconvenience. Get ready for some file location changes here soon.

**Comment by frosty00** [comment]
Nw just destroyed those commits with a git reset, cheers :0

**Comment by mikeyy** [comment]
Made a booboo, trying to fix it. **bangs head against keyboard**

**Comment by mikeyy** [comment]
Let me know how everything works out on your end...

**Comment by frosty00** [comment]
seems like both my branches have conflicts, will try resolve them tomorrow :<

**Comment by frosty00** [comment]
Closing this branch and creating a new one. Will probs be quicker than trying to solve these conflicts.

**Pull request closed without merging**
