### PR TITLE
more work on image library

### PR DESCRIPTION
**Pull request by frosty00**
Since puppeteer screenshot is broken (many people say this not just me) we will have to use a python image library to split the image into it's constituent images, getting the dimensions from the js on the page.

Will try to finish this sometime this week.

Also I keep getting this error when trying to download the audio:

```
2018-06-26 16:25:51,122 1 Clicking checkbox
2018-06-26 16:25:57,491 1 Clicking audio button
2018-06-26 16:26:09,227 1 Downloading audio file
2018-06-26 16:26:25,416 1 Status code not 101: 403 <class 'websockets.exceptions.InvalidStatusCode'>
```

not sure if this is due to using the backconnect proxy or not

### CODE REVIEW

**Comment by mikeyy** [comment]
I have another way of splitting the image I believe, with Javascript itself. I can already fetch the main image for the tiles.

This error occurs for Azure Speech API. Have you supplied an API_KEY in config.py for Azure?

**Comment by mikeyy** [comment]
I prefer parentheses to follow the same coding path of the whole library.  Mind fixing that for me on audio_url? Thanks

**Comment by frosty00** [comment]
Sorry about that, do you mind if we try to use pep8. There are ways to flake8 the entire project automatically after each commit and it will make the codebase cleaner. 

Many python editors like pycharm actually show you pep8, and it may help as the codebase increases and if more people start using it. Things that we shouldn’t do: bare except cause/ return None

**Comment by mikeyy** [comment]
No worries, I don't mind. I actually would prefer it.

> Things that we shouldn’t do: bare except cause/ return None

Agreed, those clean ups/fixes are on my backlog.

> Many python editors like pycharm actually show you pep8, and it may help as the codebase increases and if more people start using it. 

I will have to look have to look into it, thanks for the suggesstions.

**Comment by frosty00** [comment]
Yeah if you have pycharm:

> Preferences > Inspections -> PEP 8 code style 

to turn it on

**Comment by mikeyy** [comment]
I don't have pycharm. I haven't used another IDE except Coda in years, haha.

I worked on some changes with formatting and other stuff... still more to be done, of course.

**Comment by frosty00** [comment]
I think we should try to import the image parts into python anyways as there are alot of image recognition librarys written in python. Moreover, we can store a local cache of all the images and what they were labelled as if they were correct and succeeded the captca, and (eventaully) use this to train the image recognition so we can defeat it more frequently.

I read that google resends the same image captchas sometimes in the document you send me so it could be more effective than it sounds. However, this is going to take time, and I personally don't plan on finishing it for at least a couple of months.

**Comment by mikeyy** [comment]
Thanks! I will apply that in the next patch if I don't forget. Haven't forgot about this, just been busy applying fixes as they arise and more stuff to audio. Hoping to get to it soon, along with seeing if I can't fix the screenshot bug myself. If it happens to puppeteer as well, it would suck to know it's a problem with Chrome DevTools. Who knows, I'll have to look at the issue on Puppeteer's end.

**Comment by mikeyy** [comment]
>  think we should try to import the image parts into python anyways as there are alot of image recognition librarys written in python. Moreover, we can store a local cache of all the images and what they were labelled if they were correct and succeeded the captca, and (eventaully) use this to train the image recognition so we can defeat it more frequently.

I read that google resends the same image captchas so it could be more effective than it sounds. However, this is going to take time, and I personally don't plan on finishing it for at least a couple of months.

Yeah, it seems a little bit more complex than the audio route, which is why I went straight to audio at first and was like screw image solving, lol. I'm noticing reused audio's as well, I will have to start storing hashes with them as well, hopefully they don't change a byte or something to fuck it up.

**Comment by frosty00** [comment]
```
tester.py:5,1:E741:ambiguous variable name 'l
tester.py:18,1:W391:blank line at end of file
solver.py:8,1:F401:'os' imported but unused
solver.py:11,1:F401:'sys' imported but unused
solver.py:27,1:E303:too many blank lines (3)
solver.py:81,1:W293:blank line contains whitespace
solver.py:83,5:E303:too many blank lines (2)
solver.py:89,1:W293:blank line contains whitespace
solver.py:131,1:W293:blank line contains whitespace
solver.py:135,1:W293:blank line contains whitespace
solver.py:141,21:W291:trailing whitespace
solver.py:145,4:E225:missing whitespace around operator
solver.py:145,16:E225:missing whitespace around operator
solver.py:148,1:W293:blank line contains whitespace
solver.py:149,15:E225:missing whitespace around operator
solver.py:172,9:E722:do not use bare except
solver.py:176,66:W291:trailing whitespace
solver.py:188,1:W293:blank line contains whitespace
solver.py:190,1:W293:blank line contains whitespace
solver.py:196,9:E722:do not use bare except
solver.py:244,9:E722:do not use bare except
solver.py:261,9:E722:do not use bare except
solver.py:285,9:E722:do not use bare except
solver.py:317,1:W293:blank line contains whitespace
util.py:33,50:F841:local variable 'cm' is assigned to but never used
__init__.py:4,15:E401:multiple imports on one line
__init__.py:19,80:E501:line too long (136 > 79 characters)
__init__.py:38,5:F401:'config' imported but unused
__init__.py:47,16:W292:no newline at end of file
config.example.py:8,1:W293:blank line contains whitespace
config.example.py:10,1:W293:blank line contains whitespace
config.example.py:32,80:E501:line too long (81 > 79 characters)
config.example.py:39,80:E501:line too long (85 > 79 characters)
launcher.py:3,1:F401:'psutil' imported but unused
launcher.py:15,5:E265:block comment should start with '# 
launcher.py:16,32:E261:at least two spaces before inline comment
launcher.py:16,33:E262:inline comment should start with '# 
launcher.py:17,44:E261:at least two spaces before inline comment
launcher.py:17,45:E262:inline comment should start with '# 
launcher.py:18,36:E261:at least two spaces before inline comment
launcher.py:18,37:E262:inline comment should start with '# 
launcher.py:19,39:W291:trailing whitespace
launcher.py:22,26:E261:at least two spaces before inline comment
launcher.py:22,27:E262:inline comment should start with '# 
launcher.py:25,27:E261:at least two spaces before inline comment
launcher.py:25,28:E262:inline comment should start with '# 
launcher.py:26,48:E261:at least two spaces before inline comment
launcher.py:26,49:E262:inline comment should start with '# 
launcher.py:29,22:E261:at least two spaces before inline comment
launcher.py:29,23:E262:inline comment should start with '# 
launcher.py:31,28:E261:at least two spaces before inline comment
launcher.py:31,29:E262:inline comment should start with '# 
launcher.py:33,37:E261:at least two spaces before inline comment
launcher.py:33,37:E262:inline comment should start with '# 
launcher.py:36,30:E261:at least two spaces before inline comment
launcher.py:36,31:E262:inline comment should start with '# 
launcher.py:39,20:E261:at least two spaces before inline comment
launcher.py:39,21:E262:inline comment should start with '# 
launcher.py:56,27:F821:undefined name 'List
launcher.py:93,1:W293:blank line contains whitespace
launcher.py:108,9:E301:expected 1 blank line, found 0
launcher.py:130,1:W293:blank line contains whitespace
launcher.py:131,5:E303:too many blank lines (2)
audio.py:25,1:W293:blank line contains whitespace
audio.py:33,1:W293:blank line contains whitespace
audio.py:37,13:E722:do not use bare except
audio.py:67,1:W293:blank line contains whitespace
audio.py:84,9:E722:do not use bare except
audio.py:88,1:W293:blank line contains whitespace
speech.py:12,1:F401:'io.StringIO' imported but unused
speech.py:12,1:F401:'io.BytesIO' imported but unused
speech.py:34,1:E302:expected 2 blank lines, found 1
speech.py:44,1:E302:expected 2 blank lines, found 1
speech.py:48,5:F841:local variable 'wav' is assigned to but never used
speech.py:51,1:E302:expected 2 blank lines, found 1
speech.py:56,25:E203:whitespace before ':
speech.py:59,1:E302:expected 2 blank lines, found 1
image.py:6,1:E302:expected 2 blank lines, found 1
image.py:13,1:W293:blank line contains whitespace
image.py:15,9:F841:local variable 'image_url' is assigned to but never used
image.py:16,1:W293:blank line contains whitespace
image.py:39,1:W293:blank line contains whitespace
image.py:46,71:W292:no newline at end of file
base.py:26,1:W293:blank line contains whitespace
base.py:39,1:W293:blank line contains whitespace
base.py:41,66:W291:trailing whitespace
base.py:43,1:W293:blank line contains whitespace
base.py:46,1:W293:blank line contains whitespace
base.py:50,1:W293:blank line contains whitespace
base.py:51,15:E225:missing whitespace around operator
base.py:64,1:W293:blank line contains whitespace
base.py:72,1:W293:blank line contains whitespace
base.py:77,1:W293:blank line contains whitespace
base.py:78,8:E225:missing whitespace around operator
base.py:81,9:E722:do not use bare except
```

This is the output I get from running flake8. There are ways we can do automated testing and run this after every PR to ensure code quality remains good as the project grows. 

https://zonca.github.io/2017/09/automated-testing-travis-ci-github.html

**Comment by mikeyy** [comment]
That seems like an older version of nonoCAPTCHA. There shouldn't be any bare excepts left. I understand but that's the least of my worries right now unless someone wants to lend some help.

**Comment by mikeyy** [comment]
Will try to get some automated testing in this week now that I've sorted out a bunch of things on my backlog.

**Comment by frosty00** [comment]
Awesome, all the test would have to do is run run.py 10 times with different proxys until one attempt is successful. (and fail if all proxies are blocked)

At least that way we will be able to know that library still works after each change. Going to amsterdam today but should still be able to make commits this week :)

**Comment by mikeyy** [comment]
it sounds easy in theory but getting proxies that are fresh enough to even solve captchas are even a difficult task and there isn't a reliable I know of sharing the ones I use just for tests. I think we'll have to setup mock proxies or something.

**Comment by mikeyy** [comment]
Haven't got to the testing part yet but did add proxy management, at least the first commit. I feel like add() could be simplified but I haven't really thought it through. At least now you'll see what I'm trying to accomplish and could possibly make some additional changes where you feel needed

**Comment by frosty00** [comment]
Hey @mikeyy,

just looked at the new file `proxy.py` and I think we can simplify it alot. 

Firstly we really shouldn't do global imports.

```
from peewee import *
```

Secondly imo there is no need to use SqliteDatabase ever when working with python, we should just try to write the data to a file `utils.serialise` works with most objects. 

```

class Proxy(Model):
    class Meta:
        database = database
```

I don't think this is a metaclass in the traditional sense and this overcomplicates things. 

A proxy object should have these attributes:

* Last successful captcha bypass timestamp
* failed attempts at bypassing captcha (int)
* ip/port 
* authentication (if any)

I'll try write the automated testing this week for flake8 and the post-recieve hook. My only issue with travis is that it would expose the proxy credentials. Essentially, we would need to call a *private* script on another server (either yours or mine) and get the result of the tests. ssh/scp?

I've been interailling but will get back into the coding groove once I get home.

**Comment by mikeyy** [comment]
I'll keep those pointers in mine as I rewrite the code for pickling. Considering my proxies reload every 10 minutes and has a different list each time, removing some proxies while retaining others, it's imperative that we keep track of those proxies and define them according as such. If it was a one time load of the proxies list and simply managing that one list, that would be easy enough. Another problem I have with is ungraceful exits and when to pickle the data and store it in a file. I guess every reload but then there is still a chance of losing data. I guess it wouldn't be too much of an issue. Storing the pickle on a file on every go around wouldn't be the best idea neither. Maybe I'm overthinking it. In the end, yeah the code is opensource but if anything I'd rather have the object be compatible with my proxies if anything. Not to be selfish but lol.

**Comment by frosty00** [comment]
Out of curiousity how do you plan on

> Recode the backend to remove Pyppeteer dependency and complexity

**Pull request merged**
