### PR TITLE
Google reverse image search by no means complete

### PR DESCRIPTION
**Pull request by frosty00**
I saw you added some stuff for solving via image, take a look at my code and perhaps you can use it to help with yours. There may be bugs in this code and it is by no means complete. Also screenshot is crashing on mac and it is a known error with puppeteer. If it works on windows let me know.

I also added some inheritance to the library, as there were some methods that were defined twice in `AudioSolver` and `Solver`

### CODE REVIEW

**Comment by mikeyy** [comment]
Please separate commits with different purposes into their own pull request. It'll make it easier for me to review. Thanks!

**Comment by mikeyy** [comment]
> Also screenshot is crashing on mac 
That's odd, I haven't used screenshot in a few days but it was working fine for me during early trial runs several days ago and I use a Mac for development. I haven't tried screenshot on my Windows machine.

**Comment by frosty00** [comment]
@mikeyy yeah it's weird, for some reason I can take a screenshot of the whole page, but if I try to take a screenshot of one element of the image table it breaks, and freezes with just the picture I want to captiure on the screen

**Comment by frosty00** [comment]
Instead of passing methods like:

```
    log = self.log,
    check_detection = self.check_detection,
```

we should just define these on a superclass in `base.py` and share them between instances.

**Comment by mikeyy** [comment]
> if I try to take a screenshot of one element of the image table it breaks

That explains it, I've never tried creating a screenshot of an element. Most likely will fail for me too then, hah.

> Also take a look at the changes in this PR, none are particularly groundbreaking, I just moved two methods that were being repeated to a super class

Slowly making my way. I'll get to it momentarily. Sounds like a necessary adjustment.

**Comment by mikeyy** [comment]
I was actually expecting a separation of GRIS from base.py and modifications to solver.py, and  audio.py. I don't yet intend using GRIS but I'm ready to merge the new Clicker and ImageFramer modules but can't (I don't think, I'm quite an amateur at this Git) without GRIS.

**Comment by frosty00** [comment]
Ok so its real easy to do that. Make a branch off master.

```
git checkout master
git checkout -b clickerandimageframer
git checkout GRIS nonocaptcha/base.py
git add nonocaptcha/base.py
git commit -m 'a message'
git push github
```

**Comment by frosty00** [comment]
You have to add my repo as a remote first - 
```
git remote add frosty00 git@github.com:frosty00/nonoCAPTCHA.git```

**Comment by mikeyy** [comment]
Thanks! This won't recognize your contribution though, or will it?

**Comment by frosty00** [comment]
don't think so, however if you had merged my branch outside of github it would still be added to the git tree

**Pull request merged**
