### PR TITLE
add new azure speech api support

### PR DESCRIPTION
**Pull request by laalaguer**
Hi,

The "Bing" speech service will get outdated in 2019 and I have added this azure new speech api support.

Now the Speech-to-text  API in Azure needs 3 information to function properly:
1. region
2. subscription key
3. Language to detect. (eg. en-US, es-ES)

I have tested the PR with Python3 and with Spanish detection.

(By the way, always get banned from Google IP when testing, any suggestions?)

### CODE REVIEW

**Comment by laalaguer** [comment]
fix #52

**Comment by mikeyy** [comment]
Sorry for the delay, I've been focusing on other side projects. I'll take a look at why the pull request is failing under Travis and apply the proper adjustments. 

As for getting blocked by Google, multiple variables come into play but the most common is dependent on the website you are testing on has detection threshold set to maximum which hard to circumvent continuously. It's been awhile since I've went through and retested everything myself to ensure it's ability to circumvent detection measures, and possibly things may need to be reworked to have the project running properly again. I'll try and clear my schedule soon for this.

**Comment by mikeyy** [comment]
For future reference, if you click on "Details" near 
> continuous-integration/travis-ci/pr — The Travis CI build failed 

You'll find the following in the console outlining the reason for failure

```
./nonocaptcha/speech.py:181:1: E302 expected 2 blank lines, found 1
./nonocaptcha/speech.py:208:80: E501 line too long (191 > 79 characters)
./nonocaptcha/speech.py:210:80: E501 line too long (85 > 79 characters)
./nonocaptcha/audio.py:76:80: E501 line too long (81 > 79 characters)
```

**Comment by laalaguer** [comment]
Great, I didn't realize Travis can be visited besides the owner.

Now the code is fixed with pep8.

**Comment by laalaguer** [comment]
Squashed previous commits into 1 commit. :)

**Comment by mikeyy** [comment]
Thanks for your contribution. I'm merging now.

**Pull request merged**
