### PR TITLE
Adds GRIS functionality

### PR DESCRIPTION
**Pull request by frosty00**
This is the output:

```
2018-09-21 20:03:39,079 1 Starting solver with proxy None
2018-09-21 20:03:40,594 1 Clicking checkbox
Image of bus
66.249.93.85 - - [21/Sep/2018 20:03:47] "GET /5.jpg HTTP/1.1" 200 -
66.249.93.87 - - [21/Sep/2018 20:03:47] "GET /7.jpg HTTP/1.1" 200 -
66.249.93.85 - - [21/Sep/2018 20:03:47] "GET /0.jpg HTTP/1.1" 200 -
66.249.93.89 - - [21/Sep/2018 20:03:47] "GET /6.jpg HTTP/1.1" 200 -
66.249.93.89 - - [21/Sep/2018 20:03:47] "GET /2.jpg HTTP/1.1" 200 -
66.249.93.89 - - [21/Sep/2018 20:03:47] "GET /1.jpg HTTP/1.1" 200 -
66.249.93.87 - - [21/Sep/2018 20:03:47] "GET /4.jpg HTTP/1.1" 200 -
66.249.93.89 - - [21/Sep/2018 20:03:47] "GET /8.jpg HTTP/1.1" 200 -
4 Best guess for this image: tree
66.249.93.87 - - [21/Sep/2018 20:03:51] "GET /3.jpg HTTP/1.1" 200 -
5 Best guess for this image: executive car
2 Best guess for this image: bus
0 Best guess for this image: visual arts
7 Best guess for this image: animal
6 Best guess for this image: visual arts
8 Best guess for this image: notchback
1 Best guess for this image: tree
3 Best guess for this image: tree
```

Obviously there are still challenges to overcome like converting notchback to bus, but fortunately google only uses a limited number of key phrases (like store fronts, fire hydrants etc) so maybe we could use some kind of word simillarity indicator.

I am also planning on saving each successful image solve and the result to use to train an AI.

### CODE REVIEW

**Comment by mikeyy** [comment]
Nice work man, smooth progress. Mind fixing the errors for flake8 before merging? I'll review the module and see if there isn't anything I can't help out with. 

> so maybe we could use some kind of word simillarity indicator.

I agree that seems the more practical approach. I'll see if I can't whip something together for that this weekend.

> I am also planning on saving each successful image solve and the result to use to train an AI.

Hash retention for the images is definitive?

Additionally, it may be worth skipping previous puzzles that has been determined unsolvable. Preferably keeping records of each puzzle for decision making, until we feel satisfied. It may be necessary to apply a more drastic approach to some titles and block them completely. such as a whole object/title altogether.

**Comment by mikeyy** [comment]
Going to merge this before going away for a few hours.

Will get back to your comment when I return.

**Comment by mikeyy** [comment]
Haven't forgotten. Something else came up, apologies.

**Comment by frosty00** [comment]
No worries, I have already implemented a word simillarity library and will probably be done with the image clicking stuff by tomorrow. Only problem is it needs a 3gb word vector file to get trained on. 

Other good news, these are all the keys i found:

```
    all_keys = [
        'bicycle',
        'boat',
        'bridge',
        'bus',
        'car',
        'crosswalk',
        'fire hydrant',
        'mountain',
        'store front'
    ]
```

**Pull request merged**
