### PR TITLE
splits and prepares images for AI interpretation

### PR DESCRIPTION
**Pull request by frosty00**
This successfully splits an image of 9 pieces. The dimensions are always 300x300 and each image is 100x100. We would compare each image to

* Tensorflow trained on the past images (still haven't figured out how to store them)
* Google reverse image search

Example: https://imgur.com/a/zU5UpqO

screen shot 2018-09-06 at 18 01 01
screen shot 2018-09-06 at 18 13 28

We will probably also need to extract more information or somehow categorise the image, e.g. compact-mpv -> car, maybe using wikipedia?

By going to different libraries at my university I have managed to circumvent the ip detection but I don't know how much longer this tactic will work, hopefully long enough to pass image verification...

### CODE REVIEW

**Comment by BenBaltz** [comment]
I believe search the page for matches of what ur looking for. Ie. Pick all the buses, on the reverse image search page if bus in page == match

**Comment by mikeyy** [comment]
You beat me to the punch on making the line length changes. This looks good. Will push it after the Travis check has finished.

> By going to different libraries at my university I have managed to circumvent the ip detection but I don't know how much longer this tactic will work, hopefully long enough to pass image verification...

I can email you access to the new proxies but keep in mind we are set to very small bandwidth usage of 5GB.

**Comment by frosty00** [comment]
dw about emailing me the new proxies I will make do for now, I don't want to use the bandwidth by accident :-}

**Comment by mikeyy** [comment]
We could maybe use Wikipedia or come up with a method that determines the most generalized term for the "Best guess" that fits the reCAPTCHA title. Perhaps even categorizing them manually, if it's not too much work.

**Pull request merged**
